### ISSUE TITLE
Need any help?

### ISSUE THREAD

**Issue by tjnewton** [GenericMappingTools/scipy2021#2]
I would like to get up to date with all things PyGMT so I can jump back in and contribute. I'm happy to help with the tutorial if any is needed. Otherwise, I'll see you on the other side of the tutorial!

**Comment by weiji14** [comment]
Hi @tjnewton, cheers for chiming in! Just sent you an invite (by email, let me know if you didn't receive it) to the PyGMT devs slack channel where the action is happening. There's been some light discussion happening over at the forum too at https://forum.generic-mapping-tools.org/t/pygmt-at-scipy-2021/1242. We're trying to get an abstract submitted for 16 Feb so would appreciate any help on that :smile:
